Northwind/Northwind.Web/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NorthWind.BL.Interfaces;
using NorthWind.DAL;

namespace NorthWind.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService categoryService;
        public CategoryController(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        public async Task<ActionResult> Index()
        {
            var categories = await categoryService.GetCategories();
            return View(categories);
        }
    }
}

Northwind/Northwind.Web/Controllers/ProductController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using NorthWind.BL.Interfaces;
using NorthWind.DAL;
using NorthWind.Web.Mapping;
using NorthWind.Web.Models.Products;

namespace NorthWind.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService productService;
        private readonly ICategoryService categoryService;
        private readonly ISupplierService supplierService;
        private readonly IConfiguration configuration;

        public ProductController(
            IProductService productService, 
            ICategoryService categoryService, 
            ISupplierService supplierService, 
            IConfiguration configuration)
        {
            this.productService = productService;
            this.supplierService = supplierService;
            this.categoryService = categoryService;
            this.configuration = configuration;
        }

        public async Task<IActionResult> Index()
        {
            var maxProductsOnPageString = configuration["Constants:MaxProductsOnPage"];
            int.TryParse(maxProductsOnPageString, out var maxProductsOnPage);
            return View(await productService.GetListOfProductsAsync(maxProductsOnPage));
        }

        public async Task<IActionResult> Create()
        {
            ViewData["CategoryId"] = new SelectList(await categoryService.GetCategories(), "CategoryId", "CategoryName");
            ViewData["SupplierId"] = new SelectList(await supplierService.GetSuppliers(), "SupplierId", "CompanyName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateProductModel productModel)
        {
            if (ModelState.IsValid)
            {
                var product = productModel.MapToProduct();
                await productService.CreateProductAsync(product);
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(await categoryService.GetCategories(), "CategoryId", "CategoryName", productModel.CategoryId);
            ViewData["SupplierId"] = new SelectList(await supplierService.GetSuppliers(), "SupplierId", "CompanyName", productModel.SupplierId);
            return View(productModel);
        }
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await productService.GetProductAsync(id.Value);
            if (product == null)
            {
                return NotFound();
            }
            var productModel = product.MapToUpdateModel();

            ViewData["CategoryId"] = new SelectList(await categoryService.GetCategories(), "CategoryId", "CategoryName", product.CategoryId);
            ViewData["SupplierId"] = new SelectList(await supplierService.GetSuppliers(), "SupplierId", "CompanyName", product.SupplierId);
            
            return View(productModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, UpdateProductModel productModel)
        {
            if (id != productModel.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var product = productModel.MapToProduct();
                await productService.UpdateProductAsync(product);
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(await categoryService.GetCategories(), "CategoryId", "CategoryName", productModel.CategoryId);
            ViewData["SupplierId"] = new SelectList(await supplierService.GetSuppliers(), "SupplierId", "CompanyName", productModel.SupplierId);
            return View(productModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await productService.DeleteProductAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Northwind/Northwind.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NorthWind</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
            <a class="navbar-brand mb-0 h1" href="#">@ViewData["Title"]</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item active">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - NorthWind
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>